apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  source:
    path: REPLACE-ME 
    repoURL: 'https://github.com/huytn1219/fleet-test.git'
    targetRevision: HEAD
  project: default
