apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world 
  namespace: argocd 
spec:
  destination:
    name: ''
    namespace: hello-world
    server: 'https://kubernetes.default.svc'
  source:
    path: REPLACE-ME
    repoURL: 'https://github.com/huytn1219/fleet-test.git'
    targetRevision: HEAD
  project: default
