defaultNamespace: cattle-monitoring-system 
helm:
  chart: /kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts 
  releaseName: rancher-monitoring-crd
  valuesFiles:
    - ./values.yaml 
